//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phenix.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phenix.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Fill {0} {1} data... 的本地化字符串。
        /// </summary>
        public static string BindingSourceFilling {
            get {
                return ResourceManager.GetString("BindingSourceFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BindingSource Property do not allow null! 的本地化字符串。
        /// </summary>
        public static string BindingSourcePropertyIsNull {
            get {
                return ResourceManager.GetString("BindingSourcePropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to forsake editor of {0} content? 的本地化字符串。
        /// </summary>
        public static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete {0} {1} record? 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete {0} {1} record? In the finished editing and click the submit button will be officially removed 的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteMultistepSubmit {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultistepSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to execute {0}? 的本地化字符串。
        /// </summary>
        public static string ConfirmExecute {
            get {
                return ResourceManager.GetString("ConfirmExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current state in the editing, are you sure you want to exit? 的本地化字符串。
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current state in the editing, are you sure you want to refresh? 的本地化字符串。
        /// </summary>
        public static string ConfirmFetch {
            get {
                return ResourceManager.GetString("ConfirmFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records have been added, please complete the editing is submitted or cancelled 的本地化字符串。
        /// </summary>
        public static string DataAdding {
            get {
                return ResourceManager.GetString("DataAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records have been added, please complete the editing submitted or canceled, and allow in accordance with the current in content retrieval 的本地化字符串。
        /// </summary>
        public static string DataAddingOrAllowFetch {
            get {
                return ResourceManager.GetString("DataAddingOrAllowFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string DataBrowse {
            get {
                return ResourceManager.GetString("DataBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has cancelled edit {0} content 的本地化字符串。
        /// </summary>
        public static string DataCanceled {
            get {
                return ResourceManager.GetString("DataCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete records 的本地化字符串。
        /// </summary>
        public static string DataDelete {
            get {
                return ResourceManager.GetString("DataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete records {0} {1} failure: {2} 的本地化字符串。
        /// </summary>
        public static string DataDeleteAborted {
            get {
                return ResourceManager.GetString("DataDeleteAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records have been deleted, may submit or cancelled 的本地化字符串。
        /// </summary>
        public static string DataDeleting {
            get {
                return ResourceManager.GetString("DataDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export record 的本地化字符串。
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export records to file {0} failure, whether to continue to try? : {1} 的本地化字符串。
        /// </summary>
        public static string DataExportAborted {
            get {
                return ResourceManager.GetString("DataExportAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export records to {0}... 的本地化字符串。
        /// </summary>
        public static string DataExporting {
            get {
                return ResourceManager.GetString("DataExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Records have been export to file {0}, whether to need to open it? 的本地化字符串。
        /// </summary>
        public static string DataExportOpenFile {
            get {
                return ResourceManager.GetString("DataExportOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieval records 的本地化字符串。
        /// </summary>
        public static string DataFetch {
            get {
                return ResourceManager.GetString("DataFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieval records failure: {0} 的本地化字符串。
        /// </summary>
        public static string DataFetchAborted {
            get {
                return ResourceManager.GetString("DataFetchAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieval records {0}... 的本地化字符串。
        /// </summary>
        public static string DataFetching {
            get {
                return ResourceManager.GetString("DataFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful retrieval {0} record of article {1}, download only {2} seconds 的本地化字符串。
        /// </summary>
        public static string DataFetchSucceed {
            get {
                return ResourceManager.GetString("DataFetchSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieval record interrupt 的本地化字符串。
        /// </summary>
        public static string DataFetchSuspend {
            get {
                return ResourceManager.GetString("DataFetchSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import record (note the first line is listed, and all order shall not disorder) 的本地化字符串。
        /// </summary>
        public static string DataImport {
            get {
                return ResourceManager.GetString("DataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import record files {0} failure, whether to continue to try? : {1} 的本地化字符串。
        /// </summary>
        public static string DataImportAborted {
            get {
                return ResourceManager.GetString("DataImportAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import record files {0}... 的本地化字符串。
        /// </summary>
        public static string DataImporting {
            get {
                return ResourceManager.GetString("DataImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The successful implementation of {0} record of article {1}, filling, used when the {2: F3} seconds, binding used when the {3: F3} seconds, total {4: F3} seconds 的本地化字符串。
        /// </summary>
        public static string DataImportSucceed {
            get {
                return ResourceManager.GetString("DataImportSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit record, please complete the editing is submitted or cancelled 的本地化字符串。
        /// </summary>
        public static string DataModifying {
            get {
                return ResourceManager.GetString("DataModifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string DataReset {
            get {
                return ResourceManager.GetString("DataReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset failure: {0} 的本地化字符串。
        /// </summary>
        public static string DataResetAborted {
            get {
                return ResourceManager.GetString("DataResetAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset... 的本地化字符串。
        /// </summary>
        public static string DataReseting {
            get {
                return ResourceManager.GetString("DataReseting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful reset 的本地化字符串。
        /// </summary>
        public static string DataResetSucceed {
            get {
                return ResourceManager.GetString("DataResetSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore records 的本地化字符串。
        /// </summary>
        public static string DataRestore {
            get {
                return ResourceManager.GetString("DataRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore records {0} {1} failure: {2} 的本地化字符串。
        /// </summary>
        public static string DataRestoreAborted {
            get {
                return ResourceManager.GetString("DataRestoreAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit records 的本地化字符串。
        /// </summary>
        public static string DataSave {
            get {
                return ResourceManager.GetString("DataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit {0} {1} record failure: {2} 的本地化字符串。
        /// </summary>
        public static string DataSaveAborted {
            get {
                return ResourceManager.GetString("DataSaveAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit {0} {1} failure record, whether to force kept? : {2}. 的本地化字符串。
        /// </summary>
        public static string DataSaveForcibly {
            get {
                return ResourceManager.GetString("DataSaveForcibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful submission {0} record 的本地化字符串。
        /// </summary>
        public static string DataSaveSucceed {
            get {
                return ResourceManager.GetString("DataSaveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit records {0} {1}... 的本地化字符串。
        /// </summary>
        public static string DataSaving {
            get {
                return ResourceManager.GetString("DataSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefTemplate 的本地化字符串。
        /// </summary>
        public static string DefTemplateName {
            get {
                return ResourceManager.GetString("DefTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Template 的本地化字符串。
        /// </summary>
        public static string DeleteTemplate {
            get {
                return ResourceManager.GetString("DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the template {0}? 的本地化字符串。
        /// </summary>
        public static string DeleteTemplateHint {
            get {
                return ResourceManager.GetString("DeleteTemplateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Template 的本地化字符串。
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel files (*. XLS) | *. XLS | Excel 2007 files (*. XLSX) | *. XLSX 的本地化字符串。
        /// </summary>
        public static string ExcelImportFilter {
            get {
                return ResourceManager.GetString("ExcelImportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 execute {0} failure: {1} 的本地化字符串。
        /// </summary>
        public static string ExecutAborted {
            get {
                return ResourceManager.GetString("ExecutAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute method 的本地化字符串。
        /// </summary>
        public static string ExecuteMethod {
            get {
                return ResourceManager.GetString("ExecuteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful execute {0} 的本地化字符串。
        /// </summary>
        public static string ExecuteSucceed {
            get {
                return ResourceManager.GetString("ExecuteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} executing... 的本地化字符串。
        /// </summary>
        public static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel files (*. XLS) | *. XLS | Excel 2007 files (*. XLSX) | *. XLSX | text files (*. TXT) | *. TXT | page files (*. HTML) | *. HTML 的本地化字符串。
        /// </summary>
        public static string GridExportFilter {
            get {
                return ResourceManager.GetString("GridExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have template  {0} 的本地化字符串。
        /// </summary>
        public static string HaveTemplate {
            get {
                return ResourceManager.GetString("HaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The position have locked, such as mobile will be cancelled editor status, whether or not to continue? 的本地化字符串。
        /// </summary>
        public static string LockingPosition {
            get {
                return ResourceManager.GetString("LockingPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This form can open after unlock 的本地化字符串。
        /// </summary>
        public static string LockProcessHint {
            get {
                return ResourceManager.GetString("LockProcessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the file {0} failure, but not influence you to continue to homework. Please dispose of: {1} 的本地化字符串。
        /// </summary>
        public static string OpenFileAborted {
            get {
                return ResourceManager.GetString("OpenFileAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset BindingSources 的本地化字符串。
        /// </summary>
        public static string ResetBindingSources {
            get {
                return ResourceManager.GetString("ResetBindingSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset BindingSources succeed 的本地化字符串。
        /// </summary>
        public static string ResetBindingSourcesSucceed {
            get {
                return ResourceManager.GetString("ResetBindingSourcesSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset BindingSources unchanged 的本地化字符串。
        /// </summary>
        public static string ResetBindingSourcesUnchanged {
            get {
                return ResourceManager.GetString("ResetBindingSourcesUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Template 的本地化字符串。
        /// </summary>
        public static string ResetTemplate {
            get {
                return ResourceManager.GetString("ResetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset TreeListRules 的本地化字符串。
        /// </summary>
        public static string ResetTreeListRules {
            get {
                return ResourceManager.GetString("ResetTreeListRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Reset TreeListRules, please check is correct 的本地化字符串。
        /// </summary>
        public static string ResetTreeListRulesSucceed {
            get {
                return ResourceManager.GetString("ResetTreeListRulesSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data validation finished 的本地化字符串。
        /// </summary>
        public static string RuleChecked {
            get {
                return ResourceManager.GetString("RuleChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current record is invalid, please check: {0} 的本地化字符串。
        /// </summary>
        public static string RuleCheckHint {
            get {
                return ResourceManager.GetString("RuleCheckHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Template 的本地化字符串。
        /// </summary>
        public static string SwitchEditTemplate {
            get {
                return ResourceManager.GetString("SwitchEditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has been changed, save? 的本地化字符串。
        /// </summary>
        public static string SwitchEditTemplateHint {
            get {
                return ResourceManager.GetString("SwitchEditTemplateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template 的本地化字符串。
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New records 的本地化字符串。
        /// </summary>
        public static string ToolBarAddBodyTip {
            get {
                return ResourceManager.GetString("ToolBarAddBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New cloned 的本地化字符串。
        /// </summary>
        public static string ToolBarAddCloneBodyTip {
            get {
                return ResourceManager.GetString("ToolBarAddCloneBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone(&amp;C) 的本地化字符串。
        /// </summary>
        public static string ToolBarAddCloneHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarAddCloneHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New(&amp;N) 的本地化字符串。
        /// </summary>
        public static string ToolBarAddHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarAddHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to the last time submit/loading condition 的本地化字符串。
        /// </summary>
        public static string ToolBarCancelBodyTip {
            get {
                return ResourceManager.GetString("ToolBarCancelBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel(&amp;Z) 的本地化字符串。
        /// </summary>
        public static string ToolBarCancelHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarCancelHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the choice of a single/more records 的本地化字符串。
        /// </summary>
        public static string ToolBarDeleteBodyTip {
            get {
                return ResourceManager.GetString("ToolBarDeleteBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete(&amp;D) 的本地化字符串。
        /// </summary>
        public static string ToolBarDeleteHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarDeleteHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ToolBarExitBodyTip {
            get {
                return ResourceManager.GetString("ToolBarExitBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit(&amp;X) 的本地化字符串。
        /// </summary>
        public static string ToolBarExitHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarExitHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the current record... 的本地化字符串。
        /// </summary>
        public static string ToolBarExportBodyTip {
            get {
                return ResourceManager.GetString("ToolBarExportBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(&amp;O) 的本地化字符串。
        /// </summary>
        public static string ToolBarExportHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarExportHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieve records 的本地化字符串。
        /// </summary>
        public static string ToolBarFetchBodyTip {
            get {
                return ResourceManager.GetString("ToolBarFetchBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetch(&amp;F) 的本地化字符串。
        /// </summary>
        public static string ToolBarFetchHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarFetchHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string ToolBarHelpBodyTip {
            get {
                return ResourceManager.GetString("ToolBarHelpBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help(&amp;H) 的本地化字符串。
        /// </summary>
        public static string ToolBarHelpHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarHelpHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the Excel import record... 的本地化字符串。
        /// </summary>
        public static string ToolBarImportBodyTip {
            get {
                return ResourceManager.GetString("ToolBarImportBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import(&amp;I) 的本地化字符串。
        /// </summary>
        public static string ToolBarImportHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarImportHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Positioning to edit record 的本地化字符串。
        /// </summary>
        public static string ToolBarLocateBodyTip {
            get {
                return ResourceManager.GetString("ToolBarLocateBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locate(&amp;L) 的本地化字符串。
        /// </summary>
        public static string ToolBarLocateHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarLocateHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit record 的本地化字符串。
        /// </summary>
        public static string ToolBarModifyBodyTip {
            get {
                return ResourceManager.GetString("ToolBarModifyBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify(&amp;E) 的本地化字符串。
        /// </summary>
        public static string ToolBarModifyHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarModifyHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print the current record... 的本地化字符串。
        /// </summary>
        public static string ToolBarPrintBodyTip {
            get {
                return ResourceManager.GetString("ToolBarPrintBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(&amp;P) 的本地化字符串。
        /// </summary>
        public static string ToolBarPrintHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarPrintHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ToolBarResetBodyTip {
            get {
                return ResourceManager.GetString("ToolBarResetBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ToolBarResetHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarResetHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore... 的本地化字符串。
        /// </summary>
        public static string ToolBarRestoreBodyTip {
            get {
                return ResourceManager.GetString("ToolBarRestoreBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore(&amp;R) 的本地化字符串。
        /// </summary>
        public static string ToolBarRestoreHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarRestoreHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit records 的本地化字符串。
        /// </summary>
        public static string ToolBarSaveBodyTip {
            get {
                return ResourceManager.GetString("ToolBarSaveBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save(&amp;S) 的本地化字符串。
        /// </summary>
        public static string ToolBarSaveHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarSaveHeaderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup... 的本地化字符串。
        /// </summary>
        public static string ToolBarSetupBodyTip {
            get {
                return ResourceManager.GetString("ToolBarSetupBodyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup(&amp;T) 的本地化字符串。
        /// </summary>
        public static string ToolBarSetupHeaderTip {
            get {
                return ResourceManager.GetString("ToolBarSetupHeaderTip", resourceCulture);
            }
        }
    }
}
