//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phenix.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phenix.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The submitted data {0} are not allowed to save 的本地化字符串。
        /// </summary>
        public static string CheckSavableException {
            get {
                return ResourceManager.GetString("CheckSavableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The submitted data {0} do not conform to the conditions 的本地化字符串。
        /// </summary>
        public static string CheckSaveException {
            get {
                return ResourceManager.GetString("CheckSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} disabled 的本地化字符串。
        /// </summary>
        public static string DisabledRule {
            get {
                return ResourceManager.GetString("DisabledRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to execute command 的本地化字符串。
        /// </summary>
        public static string ExecuteException {
            get {
                return ResourceManager.GetString("ExecuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} Method execution not allowed 的本地化字符串。
        /// </summary>
        public static string MethodExecuteNotAllowed {
            get {
                return ResourceManager.GetString("MethodExecuteNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} Property get not allowed 的本地化字符串。
        /// </summary>
        public static string PropertyGetNotAllowed {
            get {
                return ResourceManager.GetString("PropertyGetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} Property set not allowed 的本地化字符串。
        /// </summary>
        public static string PropertySetNotAllowed {
            get {
                return ResourceManager.GetString("PropertySetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} value &apos;{1}&apos; can not be exceed {2} value &apos;{3}&apos; 的本地化字符串。
        /// </summary>
        public static string RangeCompareRule {
            get {
                return ResourceManager.GetString("RangeCompareRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable data has been restored 的本地化字符串。
        /// </summary>
        public static string RestoreDisabledException {
            get {
                return ResourceManager.GetString("RestoreDisabledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to save data 的本地化字符串。
        /// </summary>
        public static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
    }
}
