//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phenix.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phenix.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add time 的本地化字符串。
        /// </summary>
        public static string AddtimeFriendlyName {
            get {
                return ResourceManager.GetString("AddtimeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} business code format error: {1} 的本地化字符串。
        /// </summary>
        public static string BusinessCodeFormatException {
            get {
                return ResourceManager.GetString("BusinessCodeFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot connect to the {0} 的本地化字符串。
        /// </summary>
        public static string CannotConnectTo {
            get {
                return ResourceManager.GetString("CannotConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caption 的本地化字符串。
        /// </summary>
        public static string CaptionFriendlyName {
            get {
                return ResourceManager.GetString("CaptionFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before the update data {0} has been changed 的本地化字符串。
        /// </summary>
        public static string CheckDirtyException {
            get {
                return ResourceManager.GetString("CheckDirtyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exist detail records: {1} 的本地化字符串。
        /// </summary>
        public static string CheckOccupiedException {
            get {
                return ResourceManager.GetString("CheckOccupiedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exist repeat records: {1} [{2}] 的本地化字符串。
        /// </summary>
        public static string CheckRepeatedException {
            get {
                return ResourceManager.GetString("CheckRepeatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CriteriaExpression 的本地化字符串。
        /// </summary>
        public static string CriteriaExpressionFriendlyName {
            get {
                return ResourceManager.GetString("CriteriaExpressionFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Criteria 的本地化字符串。
        /// </summary>
        public static string CriteriaFriendlyName {
            get {
                return ResourceManager.GetString("CriteriaFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connection failed 的本地化字符串。
        /// </summary>
        public static string DatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database connection succeed 的本地化字符串。
        /// </summary>
        public static string DatabaseConnectionSucceed {
            get {
                return ResourceManager.GetString("DatabaseConnectionSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to delete data {0} 的本地化字符串。
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string EnabledFriendlyName {
            get {
                return ResourceManager.GetString("EnabledFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag 的本地化字符串。
        /// </summary>
        public static string FlagFriendlyName {
            get {
                return ResourceManager.GetString("FlagFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index number 的本地化字符串。
        /// </summary>
        public static string IndexNumberFriendlyName {
            get {
                return ResourceManager.GetString("IndexNumberFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to insert data {0} 的本地化字符串。
        /// </summary>
        public static string InsertException {
            get {
                return ResourceManager.GetString("InsertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string KeyFriendlyName {
            get {
                return ResourceManager.GetString("KeyFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} value &apos;{1}&apos; can not exceed {2} characters 的本地化字符串。
        /// </summary>
        public static string MaxLengthRule {
            get {
                return ResourceManager.GetString("MaxLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not implemented 的本地化字符串。
        /// </summary>
        public static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} value &apos;{1}&apos; must be at least {2} characters 的本地化字符串。
        /// </summary>
        public static string MinLengthRule {
            get {
                return ResourceManager.GetString("MinLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The failure of service 的本地化字符串。
        /// </summary>
        public static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such method {0} 的本地化字符串。
        /// </summary>
        public static string NoSuchMethod {
            get {
                return ResourceManager.GetString("NoSuchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the password is too simple(length is more than {0} and contain lowercase letters and numbers or special characters category more than {1}) 的本地化字符串。
        /// </summary>
        public static string PasswordComplexityReminder {
            get {
                return ResourceManager.GetString("PasswordComplexityReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please register &amp; enable {0} 的本地化字符串。
        /// </summary>
        public static string PleaseRegisterEnable {
            get {
                return ResourceManager.GetString("PleaseRegisterEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait 的本地化字符串。
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1}) PluginAssemblyName not allow empty 的本地化字符串。
        /// </summary>
        public static string PluginAssemblyNameRequired {
            get {
                return ResourceManager.GetString("PluginAssemblyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has been {1} lock({2} -&gt; {3}: {4}), must by {1} to unlock 的本地化字符串。
        /// </summary>
        public static string ProcessLockException {
            get {
                return ResourceManager.GetString("ProcessLockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt code 的本地化字符串。
        /// </summary>
        public static string PromptCodeFriendlyName {
            get {
                return ResourceManager.GetString("PromptCodeFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        public static string PropertyFriendlyName {
            get {
                return ResourceManager.GetString("PropertyFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read level 的本地化字符串。
        /// </summary>
        public static string ReadLevelFriendlyName {
            get {
                return ResourceManager.GetString("ReadLevelFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} not allow empty 的本地化字符串。
        /// </summary>
        public static string RequiredRule {
            get {
                return ResourceManager.GetString("RequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string SelectedFriendlyName {
            get {
                return ResourceManager.GetString("SelectedFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}, consumed {1} seconds in set DataSource 的本地化字符串。
        /// </summary>
        public static string SetDataSourceHint {
            get {
                return ResourceManager.GetString("SetDataSourceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to update data {0} 的本地化字符串。
        /// </summary>
        public static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} user has been banned login, please contact the system administrator to unlock. 的本地化字符串。
        /// </summary>
        public static string UserLockedException {
            get {
                return ResourceManager.GetString("UserLockedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 do not allow multiple address to log in 的本地化字符串。
        /// </summary>
        public static string UserMultipleAddressLoginException {
            get {
                return ResourceManager.GetString("UserMultipleAddressLoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} user without verification through! 的本地化字符串。
        /// </summary>
        public static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string UserNumberFriendlyName {
            get {
                return ResourceManager.GetString("UserNumberFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user without verification through! 的本地化字符串。
        /// </summary>
        public static string UserSignatureException {
            get {
                return ResourceManager.GetString("UserSignatureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The last operation was at {0}, still for more than {1} minutes 的本地化字符串。
        /// </summary>
        public static string UserStillTimeoutException {
            get {
                return ResourceManager.GetString("UserStillTimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The timestamp {0} are repeated! 的本地化字符串。
        /// </summary>
        public static string UserTimestampRepeatedException {
            get {
                return ResourceManager.GetString("UserTimestampRepeatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid operation - user without verification through: {0} 的本地化字符串。
        /// </summary>
        public static string UserVerifyException {
            get {
                return ResourceManager.GetString("UserVerifyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object is invalid: {0} 的本地化字符串。
        /// </summary>
        public static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string ValueFriendlyName {
            get {
                return ResourceManager.GetString("ValueFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkflowInfo {0}.{1}  does not exist 的本地化字符串。
        /// </summary>
        public static string WorkflowInfoDoesNotExist {
            get {
                return ResourceManager.GetString("WorkflowInfoDoesNotExist", resourceCulture);
            }
        }
    }
}
