//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phenix.Services.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phenix.Services.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input password please 的本地化字符串。
        /// </summary>
        public static string InputPasswordPlease {
            get {
                return ResourceManager.GetString("InputPasswordPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed! 的本地化字符串。
        /// </summary>
        public static string LogOnFailed {
            get {
                return ResourceManager.GetString("LogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify password failure 的本地化字符串。
        /// </summary>
        public static string ModifyPasswordFailed {
            get {
                return ResourceManager.GetString("ModifyPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify password was successful 的本地化字符串。
        /// </summary>
        public static string ModifyPasswordSucceed {
            get {
                return ResourceManager.GetString("ModifyPasswordSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sure you want to cancel the login? 的本地化字符串。
        /// </summary>
        public static string QuitConfirm {
            get {
                return ResourceManager.GetString("QuitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset EditFriendlyCaptions 的本地化字符串。
        /// </summary>
        public static string ResetEditFriendlyCaptions {
            get {
                return ResourceManager.GetString("ResetEditFriendlyCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Reset EditFriendlyCaptions, please check is correct 的本地化字符串。
        /// </summary>
        public static string ResetEditFriendlyCaptionsSucceed {
            get {
                return ResourceManager.GetString("ResetEditFriendlyCaptionsSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset FormRules 的本地化字符串。
        /// </summary>
        public static string ResetFormRules {
            get {
                return ResourceManager.GetString("ResetFormRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Reset FormRules, please check is correct 的本地化字符串。
        /// </summary>
        public static string ResetFormRulesSucceed {
            get {
                return ResourceManager.GetString("ResetFormRulesSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset GridFriendlyCaptions 的本地化字符串。
        /// </summary>
        public static string ResetGridFriendlyCaptions {
            get {
                return ResourceManager.GetString("ResetGridFriendlyCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Reset GridFriendlyCaptions, please check is correct 的本地化字符串。
        /// </summary>
        public static string ResetGridFriendlyCaptionsSucceed {
            get {
                return ResourceManager.GetString("ResetGridFriendlyCaptionsSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset GridFriendlyLayouts 的本地化字符串。
        /// </summary>
        public static string ResetGridFriendlyLayouts {
            get {
                return ResourceManager.GetString("ResetGridFriendlyLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset GridFriendlyLayouts is the unfinished. Please check the binding of Business class that controls the mapping relationship 的本地化字符串。
        /// </summary>
        public static string ResetGridFriendlyLayoutsAbort {
            get {
                return ResourceManager.GetString("ResetGridFriendlyLayoutsAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Reset GridFriendlyLayouts, please check is correct 的本地化字符串。
        /// </summary>
        public static string ResetGridFriendlyLayoutsSucceed {
            get {
                return ResourceManager.GetString("ResetGridFriendlyLayoutsSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ExecuteAuthorizationRules 的本地化字符串。
        /// </summary>
        public static string ShowExecuteAuthorizationRules {
            get {
                return ResourceManager.GetString("ShowExecuteAuthorizationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ReadWriteAuthorizationRules 的本地化字符串。
        /// </summary>
        public static string ShowReadWriteAuthorizationRules {
            get {
                return ResourceManager.GetString("ShowReadWriteAuthorizationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying... 的本地化字符串。
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade file 的本地化字符串。
        /// </summary>
        public static string UpgradeFile {
            get {
                return ResourceManager.GetString("UpgradeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade failure 的本地化字符串。
        /// </summary>
        public static string UpgradeFileFailed {
            get {
                return ResourceManager.GetString("UpgradeFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade was successful 的本地化字符串。
        /// </summary>
        public static string UpgradeFileSucceed {
            get {
                return ResourceManager.GetString("UpgradeFileSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade failure, whether to continue trying to download? 的本地化字符串。
        /// </summary>
        public static string UpgradeFileTry {
            get {
                return ResourceManager.GetString("UpgradeFileTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program has been upgraded, please exit after login again 的本地化字符串。
        /// </summary>
        public static string UpgradeProgramFile {
            get {
                return ResourceManager.GetString("UpgradeProgramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
