//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phenix.Core.Dictionary.Windows {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phenix.Core.Dictionary.Windows.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add successfully {0} BusinessCodeFormat: {1} 的本地化字符串。
        /// </summary>
        public static string AddBusinessCodeFormatSucceed {
            get {
                return ResourceManager.GetString("AddBusinessCodeFormatSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BusinessCodeFormat Edit: {0}[{1}] 的本地化字符串。
        /// </summary>
        public static string BusinessCodeFormatEdit {
            get {
                return ResourceManager.GetString("BusinessCodeFormatEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BusinessCodeFormat Manage 的本地化字符串。
        /// </summary>
        public static string BusinessCodeFormatManage {
            get {
                return ResourceManager.GetString("BusinessCodeFormatManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BusinessCodePlaceholderFormat Add : {0}[{1}] 的本地化字符串。
        /// </summary>
        public static string BusinessCodePlaceholderFormatAdd {
            get {
                return ResourceManager.GetString("BusinessCodePlaceholderFormatAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BusinessCodeSerialFormat Add : {0}[{1}] 的本地化字符串。
        /// </summary>
        public static string BusinessCodeSerialFormatAdd {
            get {
                return ResourceManager.GetString("BusinessCodeSerialFormatAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caption 的本地化字符串。
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When business object exists only when the following CriteriaProperty value and applying the above format 的本地化字符串。
        /// </summary>
        public static string CriteriaPropertyInfo {
            get {
                return ResourceManager.GetString("CriteriaPropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sure you want to delete the {0} BusinessCodeFormat? 的本地化字符串。
        /// </summary>
        public static string DeleteBusinessCodeFormatAsk {
            get {
                return ResourceManager.GetString("DeleteBusinessCodeFormatAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted successfully {0} BusinessCodeFormat 的本地化字符串。
        /// </summary>
        public static string DeleteBusinessCodeFormatSucceed {
            get {
                return ResourceManager.GetString("DeleteBusinessCodeFormatSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated successfully {0} BusinessCodeFormat: {1} 的本地化字符串。
        /// </summary>
        public static string EditBusinessCodeFormatSucceed {
            get {
                return ResourceManager.GetString("EditBusinessCodeFormatSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FillOnSaving 的本地化字符串。
        /// </summary>
        public static string FillOnSaving {
            get {
                return ResourceManager.GetString("FillOnSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FormatString 的本地化字符串。
        /// </summary>
        public static string FormatString {
            get {
                return ResourceManager.GetString("FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GroupMode 的本地化字符串。
        /// </summary>
        public static string GroupMode {
            get {
                return ResourceManager.GetString("GroupMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitialValue 的本地化字符串。
        /// </summary>
        public static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input CriteriaProperty value 的本地化字符串。
        /// </summary>
        public static string InputCriteriaPropertyValue {
            get {
                return ResourceManager.GetString("InputCriteriaPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LengthYear 的本地化字符串。
        /// </summary>
        public static string LengthYear {
            get {
                return ResourceManager.GetString("LengthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder 的本地化字符串。
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyName 的本地化字符串。
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResetCycle 的本地化字符串。
        /// </summary>
        public static string ResetCycle {
            get {
                return ResourceManager.GetString("ResetCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial 的本地化字符串。
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortYear 的本地化字符串。
        /// </summary>
        public static string ShortYear {
            get {
                return ResourceManager.GetString("ShortYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserNumber 的本地化字符串。
        /// </summary>
        public static string UserNumber {
            get {
                return ResourceManager.GetString("UserNumber", resourceCulture);
            }
        }
    }
}
